FROM ollama/ollama:latest

# Update and install necessary packages
RUN apt update -y && \
    apt upgrade -y && \
    apt-get install make curl -y && \
    apt autoremove -y && \
    apt autoclean -y

# Set working directory
WORKDIR /app
